# Generated by Django 4.2.7 on 2026-07-15 16:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('capacidad', models.IntegerField(default=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ambiente',
                'verbose_name_plural': 'Ambientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('horas_estimadas', models.IntegerField(default=0, help_text='Horas estimadas para la competencia')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Competencia',
                'verbose_name_plural': 'Competencias',
                'ordering': ['programa__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='FormularioPlantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Formulario',
                'verbose_name_plural': 'Formularios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FranjaHoraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
            options={
                'verbose_name': 'Franja Horaria',
                'verbose_name_plural': 'Franjas Horarias',
                'ordering': ['hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('cantidad', models.IntegerField(default=1)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('entregado', 'Entregado')], default='pendiente', max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10)),
                ('solicitante', models.CharField(blank=True, max_length=150)),
                ('departamento', models.CharField(blank=True, max_length=150)),
                ('fecha_solicitud', models.DateField(default=datetime.date.today)),
                ('fecha_respuesta', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('evaluacion_seguridad', models.JSONField(blank=True, null=True)),
                ('creado_por', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('condicion_entrega', models.CharField(blank=True, choices=[('completa', 'Entrega completa — sin observaciones'), ('parcial', 'Entrega parcial — cantidad reducida'), ('observaciones', 'Con observaciones — requiere seguimiento'), ('urgente', 'Urgente — verificación necesaria')], max_length=20, null=True)),
                ('responsable_entrega', models.CharField(blank=True, max_length=150, null=True)),
                ('notas_entrega', models.TextField(blank=True, null=True)),
                ('requiere_aprobacion_jefe', models.BooleanField(default=False)),
                ('aprobado_por_jefe', models.BooleanField(default=False)),
                ('fecha_aprobacion_jefe', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-fecha_solicitud', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Practica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ficha', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('grupos_trabajo', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobacion', 'En aprobacion'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada'), ('finalizada', 'Finalizada')], default='pendiente', max_length=20)),
                ('requiere_doble_aprobacion', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('es_recurrente', models.BooleanField(default=False)),
                ('periodicidad_dias', models.IntegerField(blank=True, help_text='Número de días entre repeticiones (ej: 2 = cada 2 días, 7 = semanal)', null=True)),
                ('fecha_ultima_repeticion', models.DateField(blank=True, null=True)),
                ('repeticiones_totales', models.IntegerField(default=1, help_text='Número total de veces que se repite')),
                ('repeticiones_realizadas', models.IntegerField(default=0)),
                ('competencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practicas', to='inventario.competencia')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practicas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('version', models.CharField(blank=True, default='1', max_length=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('simbolo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('reactivo', 'Reactivo'), ('insumo', 'Insumo'), ('equipo', 'Equipo')], max_length=20)),
                ('cantidad', models.IntegerField()),
                ('minimo', models.IntegerField()),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('unidad', models.CharField(default='unidades', max_length=30)),
                ('es_sensible', models.BooleanField(default=False, help_text='¿Este producto es sensible y requiere doble aprobación?')),
                ('horas_uso', models.IntegerField(default=0, help_text='Horas de uso del equipo')),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('serie', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='PracticaReactivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('es_sensible', models.BooleanField(default=False)),
                ('peso_inicial', models.FloatField(blank=True, help_text='Peso inicial en gramos', null=True)),
                ('peso_final', models.FloatField(blank=True, help_text='Peso final en gramos', null=True)),
                ('cantidad_consumida', models.FloatField(blank=True, help_text='Cantidad consumida', null=True)),
                ('nombre_solucion', models.CharField(blank=True, help_text='Nombre de la solución preparada', max_length=150, null=True)),
                ('concentracion', models.CharField(blank=True, help_text='Concentración de la solución', max_length=50, null=True)),
                ('cantidad_solucion_ml', models.FloatField(blank=True, help_text='Cantidad de solución en ml', null=True)),
                ('practica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactivos', to='inventario.practica')),
                ('reactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.unidadmedida')),
            ],
        ),
        migrations.CreateModel(
            name='PracticaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('cantidad_por_grupo', models.FloatField(default=0)),
                ('cantidad_total', models.FloatField(default=0)),
                ('unidad', models.CharField(default='unidades', max_length=30)),
                ('practica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='inventario.practica')),
            ],
        ),
        migrations.CreateModel(
            name='PracticaEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_uso_min', models.PositiveIntegerField()),
                ('desgaste_estimado', models.FloatField(default=0.0)),
                ('mantenimiento_requerido', models.BooleanField(default=False)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
                ('practica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='inventario.practica')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='inventario.pedido')),
                ('usuario_modificador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='inventario.producto'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PDFDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='pdfs/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(blank=True, default='', max_length=50)),
                ('referencia', models.CharField(blank=True, default='', max_length=100)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
        ),
        migrations.CreateModel(
            name='MantenimientoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo'), ('calibracion', 'Calibración'), ('predictivo', 'Predictivo')], max_length=20)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('tecnico', models.CharField(blank=True, max_length=150)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ListadoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('practica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.practica')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(blank=True, default='', max_length=100)),
                ('campo', models.CharField(blank=True, default='', max_length=100)),
                ('valor_anterior', models.TextField(blank=True, default='')),
                ('valor_nuevo', models.TextField(blank=True, default='')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FormularioRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('datos', models.JSONField(default=dict, help_text="Diccionario con respuestas: {'campo_id': 'valor'}")),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='inventario.formularioplantilla')),
                ('practica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formularios', to='inventario.practica')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formularios_respuestas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Respuesta de formulario',
                'verbose_name_plural': 'Respuestas de formularios',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='competencia',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencias', to='inventario.programa'),
        ),
        migrations.CreateModel(
            name='CampoFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Identificador interno', max_length=100)),
                ('etiqueta', models.CharField(help_text='Texto visible para el usuario', max_length=200)),
                ('tipo', models.CharField(choices=[('text', 'Texto corto'), ('textarea', 'Texto largo'), ('number', 'Número'), ('date', 'Fecha'), ('checkbox', 'Checkbox'), ('select', 'Selección')], max_length=20)),
                ('obligatorio', models.BooleanField(default=False)),
                ('opciones', models.TextField(blank=True, help_text='Para select: opción1,opción2,opción3', null=True)),
                ('orden', models.IntegerField(default=0)),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='inventario.formularioplantilla')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(default='', max_length=100)),
                ('modulo', models.CharField(default='', max_length=100)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('presente', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('practica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.practica')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('bajo_stock', 'Bajo stock'), ('vencimiento', 'Por vencer'), ('otro', 'Otro')], default='otro', max_length=50)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField(blank=True, default='')),
                ('descripcion', models.TextField(blank=True)),
                ('remitente', models.CharField(blank=True, max_length=100)),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=20)),
                ('resuelta', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('unidad', models.CharField(blank=True, default='unidades', max_length=30)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramacionLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('grupo', models.CharField(blank=True, max_length=20, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Aprobación'), ('programado', 'Programado'), ('en_curso', 'En Curso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.ambiente')),
                ('franja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.franjahoraria')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programaciones', to=settings.AUTH_USER_MODEL)),
                ('practica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programaciones', to='inventario.practica')),
            ],
            options={
                'ordering': ['fecha', 'franja', 'ambiente'],
                'unique_together': {('ambiente', 'fecha', 'franja')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='competencia',
            unique_together={('programa', 'codigo')},
        ),
    ]
