# Generated by Django 4.2.7 on 2026-05-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_sensible',
            field=models.BooleanField(default=False, help_text='¿Este producto es sensible y requiere doble aprobación?'),
        ),
    ]
