# Generated by Django 4.2.7 on 2026-04-16 14:40

import datetime
from django.conf import settings

class UserProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='profile')
    # ...otros campos...

class UserProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='profile')
    # ...otros campos...
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0002_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='ayuda', max_length=50)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('estado', models.CharField(choices=[('nueva', 'Nueva'), ('resuelta', 'Resuelta')], default='nueva', max_length=20)),
                ('remitente', models.CharField(blank=True, default='Sistema', max_length=150)),
                ('destinatario', models.CharField(blank=True, default='Admin y Jefe', max_length=150)),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='movimiento',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-fecha_solicitud', '-id']},
        ),
        migrations.AddField(
            model_name='pedido',
            name='codigo',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='creado_por',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='departamento',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='pedido',
            name='evaluacion_seguridad',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_respuesta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_solicitud',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='pedido',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='prioridad',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='solicitante',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='producto',
            name='ultima_actualizacion',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.producto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='inventario.producto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='inventario.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='minimo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('reactivo', 'Reactivo'), ('insumo', 'Insumo'), ('equipo', 'Equipo')], default='reactivo', max_length=20),
        ),
    ]
