# Generated by Django 4.2.7 on 2026-05-12 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_producto_es_sensible'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='practica',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='practica',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobacion', 'En aprobacion'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada'), ('finalizada', 'Finalizada')], default='pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='PracticaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('cantidad_por_grupo', models.FloatField(default=0)),
                ('cantidad_total', models.FloatField(default=0)),
                ('practica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='inventario.practica')),
            ],
        ),
        migrations.RemoveField(
            model_name='practica',
            name='admin_aprobado',
        ),
        migrations.RemoveField(
            model_name='practica',
            name='jefe_aprobado',
        ),
        migrations.RemoveField(
            model_name='practica',
            name='pdf',
        ),
    ]
