# Generated by Django for Auditoria model
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_userprofile'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('crear', 'Crear'), ('editar', 'Editar'), ('eliminar', 'Eliminar'), ('aprobar', 'Aprobar'), ('rechazar', 'Rechazar')], max_length=20)),
                ('modulo', models.CharField(choices=[('inventario', 'Inventario'), ('pedidos', 'Pedidos'), ('usuarios', 'Usuarios'), ('alertas', 'Alertas')], max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to='auth.user')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
