# Generated by Django 4.2.7 on 2026-04-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_auditoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
