# Generated by Django 4.2.7 on 2026-05-21 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_programa_competencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='practica',
            name='competencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practicas', to='inventario.competencia'),
        ),
    ]
