# Generated by Django 4.2.7 on 2026-05-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_practica_competencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='practica',
            name='es_recurrente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='practica',
            name='fecha_ultima_repeticion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='practica',
            name='periodicidad_dias',
            field=models.IntegerField(blank=True, help_text='Número de días entre repeticiones (ej: 2 = cada 2 días, 7 = semanal)', null=True),
        ),
        migrations.AddField(
            model_name='practica',
            name='repeticiones_realizadas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='practica',
            name='repeticiones_totales',
            field=models.IntegerField(default=1, help_text='Número total de veces que se repite'),
        ),
    ]
