# Generated by Django 4.2.7 on 2026-05-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_practica_es_recurrente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='aprobado_por_jefe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_aprobacion_jefe',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='requiere_aprobacion_jefe',
            field=models.BooleanField(default=False),
        ),
    ]
