# Generated by Django 4.2.7 on 2026-05-29 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0008_pedido_aprobado_por_jefe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioPlantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Formulario',
                'verbose_name_plural': 'Formularios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormularioRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('datos', models.JSONField(default=dict, help_text="Diccionario con respuestas: {'campo_id': 'valor'}")),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='inventario.formularioplantilla')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formularios_respuestas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Respuesta de formulario',
                'verbose_name_plural': 'Respuestas de formularios',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='CampoFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Identificador interno', max_length=100)),
                ('etiqueta', models.CharField(help_text='Texto visible para el usuario', max_length=200)),
                ('tipo', models.CharField(choices=[('text', 'Texto corto'), ('textarea', 'Texto largo'), ('number', 'Número'), ('date', 'Fecha'), ('checkbox', 'Checkbox'), ('select', 'Selección')], max_length=20)),
                ('obligatorio', models.BooleanField(default=False)),
                ('opciones', models.TextField(blank=True, help_text='Para select: opción1,opción2,opción3', null=True)),
                ('orden', models.IntegerField(default=0)),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='inventario.formularioplantilla')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
