# Generated by Django 4.2.7 on 2026-06-22 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0010_mantenimientoequipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('capacidad', models.IntegerField(default=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ambiente',
                'verbose_name_plural': 'Ambientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='FranjaHoraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
            options={
                'verbose_name': 'Franja Horaria',
                'verbose_name_plural': 'Franjas Horarias',
                'ordering': ['hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ProgramacionLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('grupo', models.CharField(blank=True, max_length=20, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.ambiente')),
                ('franja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.franjahoraria')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programaciones', to=settings.AUTH_USER_MODEL)),
                ('practica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programaciones', to='inventario.practica')),
            ],
            options={
                'verbose_name': 'Programación de Laboratorio',
                'verbose_name_plural': 'Programaciones de Laboratorio',
                'ordering': ['fecha', 'franja', 'ambiente'],
                'unique_together': {('ambiente', 'fecha', 'franja')},
            },
        ),
    ]
