# Generated by Django 4.2.7 on 2026-06-23 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_ambiente_franjahoraria_programacionlaboratorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulariorespuesta',
            name='practica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formularios', to='inventario.practica'),
        ),
    ]
