# Generated by Django 4.2.7 on 2026-07-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_producto_fecha_compra_producto_marca_producto_modelo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacionlaboratorio',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programacionlaboratorio',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
