# Generated by Django 4.2.7 on 2026-07-31 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0014_programacionlaboratorio_hora_fin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programacionlaboratorio',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='programacionlaboratorio',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='programacionlaboratorio',
            name='estado',
            field=models.CharField(default='programado', max_length=20),
        ),
        migrations.AlterField(
            model_name='programacionlaboratorio',
            name='grupo',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='programacionlaboratorio',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='programacionlaboratorio',
            name='observaciones',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='programacionlaboratorio',
            name='practica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.practica'),
        ),
        migrations.AlterUniqueTogether(
            name='programacionlaboratorio',
            unique_together={('practica', 'fecha', 'ambiente', 'franja')},
        ),
    ]
