# Generated by Django 4.2.7 on 2026-04-30 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_ensure_admin_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email_verification_attempts',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email_verification_code_expires_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email_verification_code_hash',
        ),
    ]
