# Generated by Django 4.2.7 on 2026-07-31 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_alter_programacionlaboratorio_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacionlaboratorio',
            name='creado_por',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
