# Generated by Django 4.2.7 on 2026-07-31 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_programacionlaboratorio_creado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacionlaboratorio',
            name='creado_por',
            field=models.CharField(blank=True, default='admin', max_length=150, null=True),
        ),
    ]
