# Generated by Django 4.2.7 on 2026-08-28 20:20

from django.db import migrations, models


def limpiar_productos_invalidos(apps, schema_editor):
    Alerta = apps.get_model('inventario', 'Alerta')
    Producto = apps.get_model('inventario', 'Producto')
    ids_validos = Producto.objects.values_list('id', flat=True)
    Alerta.objects.filter(producto_id__isnull=False).exclude(producto_id__in=ids_validos).update(producto=None)


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0017_alter_programacionlaboratorio_creado_por'),
    ]

    operations = [
        migrations.RunPython(limpiar_productos_invalidos, migrations.RunPython.noop),
        migrations.AddField(
            model_name='alerta',
            name='acciones_tomadas',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='alerta',
            name='soluciones_aplicadas',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
