# Generated by Django 4.2.7 on 2026-08-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0017_alter_programacionlaboratorio_creado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='acciones_tomadas',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='alerta',
            name='soluciones_aplicadas',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
